// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:8d8cb6f8-9b92-4c58-a519-ad61e0c7e8df",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_5wLgbdGsg",
    "aws_user_pools_web_client_id": "ihf5bdhf3d2puj0bva12e1epb",
    "oauth": {}
};


export default awsmobile;
